---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: config

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: config
subjects:
  - kind: ServiceAccount
    name: default
    namespace: default
roleRef:
  kind: ClusterRole
  name: cluster-admin
  apiGroup: rbac.authorization.k8s.io


---
apiVersion: v1
kind: Pod
metadata:
  name: cconfig
spec:
  serviceAccountName: config
  containers:
    - name: cconfig
      image: storidge/cconfig

