apiVersion: v1
kind: Pod
metadata:
  name: secret-test-pod
spec:
  containers:
    - name: test-container
      image: nginx
      volumeMounts:
        - name: secret-volume
          mountPath: /secret
        - name: storidge
          mountPath: /storidge
  volumes:
    - name: secret-volume
      secret:
        secretName: storidge-config
    - name: storidge
      hostPath:
        path: /etc/storidge/config
        type: Directory
